# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  evergarden = {
    pname = "evergarden";
    version = "b49ee5bef999955e688ea883a1f7b14cd41de8b4";
    src = fetchgit {
      url = "https://codeberg.org/evergarden/nvim";
      rev = "b49ee5bef999955e688ea883a1f7b14cd41de8b4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-55iIlWrwqtaAaOPbgmKXd5d9U4Y9ICBRJudh2VSNRxg=";
    };
    as = "evergarden";
    date = "2026-01-21";
  };
  lynn-nvim = {
    pname = "lynn-nvim";
    version = "1721a5a524b49232a367a3c9215adfa4e99644c4";
    src = fetchgit {
      url = "https://codeberg.org/comfysage/lynn.nvim";
      rev = "1721a5a524b49232a367a3c9215adfa4e99644c4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tQ3vFI8iANLOnf97wF5H5uHnKWlarMTqNqexK06XRpQ=";
    };
    as = "lynn";
    start = "true";
    date = "2026-01-04";
  };
}
